# .github/workflows/build_and_publish.yml

name: Build and Publish to PyPI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# by default, permissions are read-only, read + write is required for git pushes
permissions:
  contents: write

jobs:
  matrix-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13", "3.12", "3.11", "3.10", "3.9", "3.8"]
    steps:
      - uses: actions/checkout@v4
      - name: ASDF Parse
        uses: kota65535/github-asdf-parse-action@v2.0.0
        id: versions
      - uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python-version }}"
      - uses: abatilo/actions-poetry@v4.0.0
        with:
          poetry-version: "${{ steps.versions.outputs.poetry }}"
      - run: pip install .
      # TODO actually have a very basic test suite
      # - run: pytest -v
      - run: python -c "from rpdb import set_trace"

  build-and-publish:
    if: github.ref == 'refs/heads/master'
    needs: matrix-test
    # this package is tied to macos-specific libraries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ASDF Parse
        uses: kota65535/github-asdf-parse-action@v2.0.0
        id: versions

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ steps.versions.outputs.python }}"

      - name: Install Poetry
        uses: Gr1N/setup-poetry@v9
        with:
          poetry-version: "${{ steps.versions.outputs.poetry }}"

      - name: Install dependencies
        run: |
          poetry install

      # - name: Conventional Changelog Action
      #   id: changelog
      #   uses: TriPSs/conventional-changelog-action@v5
      #   with:
      #     github-token: ${{ secrets.github_token }}
      #     version-file: ./pyproject.toml
      #     version-path: tool.poetry.version
      #     fallback-version: 0.1.0
      #     output-file: CHANGELOG.md

      # # NOTE must run after versioning otherwise the right version won't be pushed
      # - name: Build distribution package
      #   if: ${{ steps.changelog.outputs.skipped == 'false' }}
      #   run: |
      #     poetry build

      # - name: Publish to PyPI
      #   if: ${{ steps.changelog.outputs.skipped == 'false' }}
      #   run: |
      #     # `gh secret set PYPI_API_TOKEN --app actions --body $PYPI_API_TOKEN`
      #     poetry publish -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}

      # - name: Github Release
      #   if: ${{ steps.changelog.outputs.skipped == 'false' }}
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     # output options: https://github.com/TriPSs/conventional-changelog-action#outputs
      #     body: ${{ steps.changelog.outputs.clean_changelog }}
      #     tag_name: ${{ steps.changelog.outputs.tag }}
